JAT-104 Add functionality to clear/reset AQUA settings to "default"
h39s/AQUA pull request #58
Opened 2023-09-22 01:27 UTC by selinali2010

# Summary
- Add option to clear gains on all filters
- Add options to reset parametric EQ to a fixed band EQ

## Changes
- Add headers for the "Auto EQ" and "Parametric EQ" sections
- Add constants for the frequencies for fixed bands
- Add new functions `clearGains` and `setFixedBand` 

## Screenshots
![image](https://github.com/h39s/AQUA/assets/30204513/581bb374-fffb-4ae9-ba1f-c1fc5a488de3)

## Tests
-

2023-10-01 19:08 UTC, h39s approved these changes
LGTM! Tested locally for now, it is very nice that clear gains doesn't affect pre-amp unless auto pre-amp is on!

2023-10-02 03:40 UTC, chintav1 approved these changes

2023-10-02 04:09 UTC, xenown requested changes
Apart from Set Fixed Band, LGTM.

2023-10-03 00:44 UTC, selinali2010 commented on src/main/main.ts
> +  const size: FixedBandSizeEnum = arg[0];
Added a helper to validate enum values

2023-10-06 06:12 UTC, xenown approved these changes
LGTM

2023-10-08 04:14 UTC, merged